# Dockerfile.locust

FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY performance_tests/ /app/performance_tests/

CMD ["locust", "-f", "performance_tests/locustfile.py"]
