# Use a Python image for testing
FROM python:3.10-slim AS test

# Install system dependencies required for testing
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    default-libmysqlclient-dev \
    wget \
    unzip \
    xvfb \
    libxi6 \
    libgconf-2-4

# Install Chrome and ChromeDriver for testing (if required)
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
    apt-get update && \
    apt-get install -y google-chrome-stable && \
    wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/ && \
    rm /tmp/chromedriver.zip

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV CHROME_DRIVER_PATH /usr/local/bin/chromedriver

# Set working directory
WORKDIR /app

# Copy requirements for testing
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the test files
COPY scalable_data_warehouse/ scalable_data_warehouse/

# Run tests
CMD ["pytest", "scalable_data_warehouse/airflow/tests/"]
